### ISSUE TITLE
Format specification

### ISSUE THREAD

**Issue by maxwellb** [mscdex/nodebench#1]
I'd like to open this issue to discuss the format you are using, in order to facilitate possible issues from parsing or consuming your results.

At the current time, I'll start with an open ended question: what are your current thoughts regarding the format that is currently used? (For example, are there any plans to adjust the file layout or JSON formats, or in general how stable is this repo for others to consume)

Thank you!

**Comment by mscdex** [comment]
As far as the data itself goes, I don't have any plans to change the format/structure at the moment.

Do you have any specific questions/concerns about the existing format?

**Comment by maxwellb** [comment]
I do not have any specific questions or concerns, no. Thank you for providing the tests and the data.

Would you like me to close this issue, or leave it open to add notes as I integrate with the dataset?

**Comment by mscdex** [comment]
I'll close this out for now.
